#!/usr/bin/env sh

echo "=== Running Frontend Checks ==="
cd frontend
npm run lint || exit 1
npm run build || exit 1
cd ..

echo "=== Running Backend Checks ==="
cd backend
npm run lint || exit 1
npm run build || exit 1
cd ..
